name: create iso on push

on:
  push:
    branches:
      - main

jobs:
  create-iso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install genisoimage
      run: sudo apt-get update && sudo apt-get install -y genisoimage

    - name: Prepare ISO content
      run: |
        mkdir iso_temp
        find . -maxdepth 1 -type f ! -name '*.md' ! -name '.gitignore' ! -name '*.yml' ! -name '*.yaml' ! -name 'FNAF5.elf' -exec cp {} iso_temp/ \;
        for dir in */; do
          if [[ "$dir" != ".git/" && "$dir" != ".github/" && "$dir" != "iso_temp/" ]]; then
            cp -r "$dir" iso_temp/
          fi
        done
        if [ -d "PS2DATA/DATA/ISOF" ]; then
          cp -r PS2DATA/DATA/ISOF/* iso_temp/
        fi
        rm -rf iso_temp/.git
        find iso_temp -type f | head -20

    - name: Create ISO
      run: |
        genisoimage -o FNAF5PS2.iso -R -J -V "FNAF5PS2" iso_temp/
        ls -la FNAF5PS2.iso

    - name: Upload ISO Artifact
      uses: actions/upload-artifact@v4
      with:
        name: fnaf5-ps2-iso
        path: FNAF5PS2.iso
